# Generated by Django 5.2.1 on 2025-05-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cvs", "0002_hardskill_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="photos",
            name="description",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
