# Generated by Django 5.2.3 on 2025-06-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cvs", "0002_remove_case_block_name_remove_education_block_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="header",
            name="city_title",
            field=models.CharField(default="City", max_length=50),
        ),
        migrations.AddField(
            model_name="header",
            name="country_title",
            field=models.CharField(default="Country", max_length=50),
        ),
        migrations.AddField(
            model_name="header",
            name="disctrict_title",
            field=models.CharField(default="District", max_length=50),
        ),
    ]
