# Generated by Django 5.2.1 on 2025-06-01 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cvs", "0003_photos_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="languagechoice",
            old_name="name",
            new_name="lang",
        ),
        migrations.RemoveField(
            model_name="languagechoice",
            name="code",
        ),
    ]
