# Generated by Django 5.2.3 on 2025-06-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cvs", "0003_header_city_title_header_country_title_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="header",
            name="city_title",
        ),
        migrations.RemoveField(
            model_name="header",
            name="country_title",
        ),
        migrations.RemoveField(
            model_name="header",
            name="disctrict_title",
        ),
        migrations.AddField(
            model_name="blocknames",
            name="city_title",
            field=models.CharField(default="City", max_length=50),
        ),
        migrations.AddField(
            model_name="blocknames",
            name="country_title",
            field=models.CharField(default="Country", max_length=50),
        ),
        migrations.AddField(
            model_name="blocknames",
            name="district_title",
            field=models.CharField(default="District", max_length=50),
        ),
    ]
