# Generated by Django 5.2.3 on 2025-06-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cvs", "0004_remove_header_city_title_remove_header_country_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blocknames",
            name="city_title",
            field=models.CharField(default="City: ", max_length=50),
        ),
        migrations.AlterField(
            model_name="blocknames",
            name="country_title",
            field=models.CharField(default="Country: ", max_length=50),
        ),
        migrations.AlterField(
            model_name="blocknames",
            name="district_title",
            field=models.CharField(default="District: ", max_length=50),
        ),
    ]
