# Generated by Django 5.2.1 on 2025-06-01 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cvs", "0004_rename_name_languagechoice_lang_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hardskill",
            name="language",
            field=models.ForeignKey(
                default=4,
                on_delete=django.db.models.deletion.CASCADE,
                to="cvs.languagechoice",
            ),
            preserve_default=False,
        ),
    ]
