# Generated by Django 5.2.3 on 2025-06-20 10:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cvs", "0005_alter_blocknames_city_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="manifest",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="manifest",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
