# Generated by Django 5.2.1 on 2025-06-01 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cvs", "0005_hardskill_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="hardskill",
            name="block_name",
            field=models.CharField(default="Hard Skills", max_length=30),
        ),
    ]
