# Generated by Django 5.2.3 on 2025-06-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cvs", "0006_manifest_created_at_manifest_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="blocknames",
            name="achievements_title",
            field=models.CharField(default="Achievements", max_length=50),
        ),
        migrations.AddField(
            model_name="blocknames",
            name="company_title",
            field=models.CharField(default="Company", max_length=50),
        ),
        migrations.AddField(
            model_name="blocknames",
            name="contacts_title",
            field=models.CharField(default="Contacts", max_length=50),
        ),
        migrations.AddField(
            model_name="blocknames",
            name="degree_title",
            field=models.CharField(default="Degree", max_length=50),
        ),
        migrations.AddField(
            model_name="blocknames",
            name="ed_period_title",
            field=models.CharField(default="Period", max_length=50),
        ),
        migrations.AddField(
            model_name="blocknames",
            name="exp_period_title",
            field=models.CharField(default="Period", max_length=50),
        ),
        migrations.AddField(
            model_name="blocknames",
            name="institution_title",
            field=models.CharField(default="Institution", max_length=50),
        ),
        migrations.AddField(
            model_name="blocknames",
            name="level_title",
            field=models.CharField(default="level: ", max_length=50),
        ),
        migrations.AddField(
            model_name="blocknames",
            name="optimization_title",
            field=models.CharField(default="Optimization", max_length=50),
        ),
        migrations.AddField(
            model_name="blocknames",
            name="position_title",
            field=models.CharField(default="Position", max_length=50),
        ),
        migrations.AddField(
            model_name="blocknames",
            name="result_title",
            field=models.CharField(default="Result", max_length=50),
        ),
        migrations.AddField(
            model_name="blocknames",
            name="solution_title",
            field=models.CharField(default="Solution", max_length=50),
        ),
        migrations.AddField(
            model_name="blocknames",
            name="task_title",
            field=models.CharField(default="Task", max_length=50),
        ),
        migrations.AddField(
            model_name="blocknames",
            name="tech_stack_title",
            field=models.CharField(default="Teck Stack", max_length=50),
        ),
    ]
