# Generated by Django 5.2.1 on 2025-06-01 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cvs", "0006_hardskill_block_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hardskill",
            old_name="language",
            new_name="lang",
        ),
        migrations.RemoveField(
            model_name="hardskill",
            name="block_name",
        ),
        migrations.CreateModel(
            name="BlockNames",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("header_name", models.CharField(default="Header", max_length=100)),
                (
                    "hard_skills_name",
                    models.CharField(default="Hard Skills", max_length=100),
                ),
                ("manifest_name", models.CharField(default="Manifest", max_length=100)),
                ("projects_name", models.CharField(default="Projects", max_length=100)),
                (
                    "experience_name",
                    models.CharField(default="Experience", max_length=100),
                ),
                (
                    "soft_skills_name",
                    models.CharField(default="Soft Skills", max_length=100),
                ),
                (
                    "education_name",
                    models.CharField(default="Education", max_length=100),
                ),
                ("hobby_name", models.CharField(default="Hobby", max_length=100)),
                ("cases_name", models.CharField(default="Cases", max_length=100)),
                ("why_me_name", models.CharField(default="Why me?", max_length=100)),
                (
                    "lang",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cvs.languagechoice",
                    ),
                ),
            ],
        ),
    ]
