# Generated by Django 5.2.3 on 2025-06-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cvs", "0007_blocknames_achievements_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blocknames",
            name="tech_stack_title",
            field=models.CharField(default="Tech Stack", max_length=50),
        ),
    ]
