# Generated by Django 5.2.1 on 2025-06-01 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cvs", "0007_rename_language_hardskill_lang_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hardskill",
            name="block_name",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.CASCADE,
                to="cvs.blocknames",
            ),
            preserve_default=False,
        ),
    ]
