# Generated by Django 5.2.3 on 2025-06-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cvs", "0008_alter_blocknames_tech_stack_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="blocknames",
            name="current",
            field=models.CharField(default="current", max_length=50),
        ),
    ]
