# Generated by Django 5.2.1 on 2025-06-01 09:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cvs", "0008_hardskill_block_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="blocknames",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="blocknames",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
