# Generated by Django 5.2.3 on 2025-06-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cvs", "0009_blocknames_current"),
    ]

    operations = [
        migrations.AddField(
            model_name="blocknames",
            name="github_title",
            field=models.CharField(default="github", max_length=50),
        ),
        migrations.AddField(
            model_name="blocknames",
            name="linkedin_title",
            field=models.CharField(default="linkedin", max_length=50),
        ),
    ]
