# Generated by Django 5.2.1 on 2025-06-01 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cvs", "0009_blocknames_created_at_blocknames_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="header",
            name="lang",
            field=models.ForeignKey(
                default=4,
                on_delete=django.db.models.deletion.CASCADE,
                to="cvs.languagechoice",
            ),
            preserve_default=False,
        ),
    ]
