# Generated by Django 5.2.12 on 2026-03-22 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cvs", "0011_alter_blocknames_achievements_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interest",
            name="interest_text",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="whyme",
            name="company",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="whyme",
            name="why_me_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
