# Generated by Django 5.2.1 on 2025-06-02 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cvs", "0011_manifest_lang_manifest_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="lang",
            field=models.ForeignKey(
                default=4,
                on_delete=django.db.models.deletion.CASCADE,
                to="cvs.languagechoice",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="project_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
