# Generated by Django 5.2.1 on 2025-06-02 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cvs", "0012_project_lang_project_project_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="project_url",
            new_name="git_url",
        ),
        migrations.AddField(
            model_name="project",
            name="web_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
