# Generated by Django 5.2.1 on 2026-04-17 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cvs", "0013_directurl"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DirectUrl",
        ),
    ]
