# Generated by Django 5.2.1 on 2025-06-03 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cvs", "0013_rename_project_url_project_git_url_project_web_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="experience",
            old_name="job_title",
            new_name="position",
        ),
    ]
