# Generated by Django 5.2.1 on 2026-04-17 07:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cvs", "0014_delete_directurl"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blocknames",
            name="occupation",
        ),
        migrations.RemoveField(
            model_name="blocknames",
            name="user",
        ),
        migrations.RemoveField(
            model_name="case",
            name="occupation",
        ),
        migrations.RemoveField(
            model_name="case",
            name="user",
        ),
        migrations.RemoveField(
            model_name="education",
            name="occupation",
        ),
        migrations.RemoveField(
            model_name="education",
            name="user",
        ),
        migrations.RemoveField(
            model_name="experience",
            name="occupation",
        ),
        migrations.RemoveField(
            model_name="experience",
            name="user",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="occupation",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="user",
        ),
        migrations.RemoveField(
            model_name="hardskill",
            name="occupation",
        ),
        migrations.RemoveField(
            model_name="hardskill",
            name="user",
        ),
        migrations.RemoveField(
            model_name="header",
            name="occupation",
        ),
        migrations.RemoveField(
            model_name="header",
            name="user",
        ),
        migrations.RemoveField(
            model_name="interest",
            name="occupation",
        ),
        migrations.RemoveField(
            model_name="interest",
            name="user",
        ),
        migrations.RemoveField(
            model_name="manifest",
            name="occupation",
        ),
        migrations.RemoveField(
            model_name="manifest",
            name="user",
        ),
        migrations.RemoveField(
            model_name="naturallanguage",
            name="occupation",
        ),
        migrations.RemoveField(
            model_name="naturallanguage",
            name="user",
        ),
        migrations.RemoveField(
            model_name="photos",
            name="lang",
        ),
        migrations.RemoveField(
            model_name="photos",
            name="occupation",
        ),
        migrations.RemoveField(
            model_name="photos",
            name="user",
        ),
        migrations.RemoveField(
            model_name="project",
            name="occupation",
        ),
        migrations.RemoveField(
            model_name="project",
            name="user",
        ),
        migrations.RemoveField(
            model_name="softskill",
            name="occupation",
        ),
        migrations.RemoveField(
            model_name="softskill",
            name="user",
        ),
        migrations.RemoveField(
            model_name="whyme",
            name="occupation",
        ),
        migrations.RemoveField(
            model_name="whyme",
            name="user",
        ),
        migrations.AlterField(
            model_name="blocknames",
            name="achievements_title",
            field=models.CharField(default="Achievements", max_length=50),
        ),
        migrations.AlterField(
            model_name="blocknames",
            name="cases_name",
            field=models.CharField(default="Cases", max_length=100),
        ),
        migrations.AlterField(
            model_name="blocknames",
            name="city_title",
            field=models.CharField(default="City: ", max_length=50),
        ),
        migrations.AlterField(
            model_name="blocknames",
            name="company_title",
            field=models.CharField(default="Company", max_length=50),
        ),
        migrations.AlterField(
            model_name="blocknames",
            name="contacts_title",
            field=models.CharField(default="Contacts", max_length=50),
        ),
        migrations.AlterField(
            model_name="blocknames",
            name="country_title",
            field=models.CharField(default="Country: ", max_length=50),
        ),
        migrations.AlterField(
            model_name="blocknames",
            name="current",
            field=models.CharField(default="current", max_length=50),
        ),
        migrations.AlterField(
            model_name="blocknames",
            name="degree_title",
            field=models.CharField(default="Degree", max_length=50),
        ),
        migrations.AlterField(
            model_name="blocknames",
            name="district_title",
            field=models.CharField(default="District: ", max_length=50),
        ),
        migrations.AlterField(
            model_name="blocknames",
            name="ed_period_title",
            field=models.CharField(default="Period", max_length=50),
        ),
        migrations.AlterField(
            model_name="blocknames",
            name="education_name",
            field=models.CharField(default="Education", max_length=100),
        ),
        migrations.AlterField(
            model_name="blocknames",
            name="exp_period_title",
            field=models.CharField(default="Period", max_length=50),
        ),
        migrations.AlterField(
            model_name="blocknames",
            name="experience_name",
            field=models.CharField(default="Experience", max_length=100),
        ),
        migrations.AlterField(
            model_name="blocknames",
            name="feedback_name",
            field=models.CharField(default="Feedback", max_length=100),
        ),
        migrations.AlterField(
            model_name="blocknames",
            name="github_title",
            field=models.CharField(default="github", max_length=50),
        ),
        migrations.AlterField(
            model_name="blocknames",
            name="hard_skills_name",
            field=models.CharField(default="Hard Skills", max_length=100),
        ),
        migrations.AlterField(
            model_name="blocknames",
            name="header_name",
            field=models.CharField(default="Header", max_length=100),
        ),
        migrations.AlterField(
            model_name="blocknames",
            name="institution_title",
            field=models.CharField(default="Institution", max_length=50),
        ),
        migrations.AlterField(
            model_name="blocknames",
            name="interest_name",
            field=models.CharField(default="Interests", max_length=100),
        ),
        migrations.AlterField(
            model_name="blocknames",
            name="level_title",
            field=models.CharField(default="level: ", max_length=50),
        ),
        migrations.AlterField(
            model_name="blocknames",
            name="linkedin_title",
            field=models.CharField(default="linkedin", max_length=50),
        ),
        migrations.AlterField(
            model_name="blocknames",
            name="manifest_name",
            field=models.CharField(default="Manifest", max_length=100),
        ),
        migrations.AlterField(
            model_name="blocknames",
            name="natural_lang_name",
            field=models.CharField(default="Natural Languages", max_length=100),
        ),
        migrations.AlterField(
            model_name="blocknames",
            name="optimization_title",
            field=models.CharField(default="Optimization", max_length=50),
        ),
        migrations.AlterField(
            model_name="blocknames",
            name="photo_name",
            field=models.CharField(default="Photo", max_length=100),
        ),
        migrations.AlterField(
            model_name="blocknames",
            name="position_title",
            field=models.CharField(default="Position", max_length=50),
        ),
        migrations.AlterField(
            model_name="blocknames",
            name="projects_name",
            field=models.CharField(default="Projects", max_length=100),
        ),
        migrations.AlterField(
            model_name="blocknames",
            name="result_title",
            field=models.CharField(default="Result", max_length=50),
        ),
        migrations.AlterField(
            model_name="blocknames",
            name="soft_skills_name",
            field=models.CharField(default="Soft Skills", max_length=100),
        ),
        migrations.AlterField(
            model_name="blocknames",
            name="solution_title",
            field=models.CharField(default="Solution", max_length=50),
        ),
        migrations.AlterField(
            model_name="blocknames",
            name="task_title",
            field=models.CharField(default="Task", max_length=50),
        ),
        migrations.AlterField(
            model_name="blocknames",
            name="tech_stack_title",
            field=models.CharField(default="Tech Stack", max_length=50),
        ),
        migrations.AlterField(
            model_name="blocknames",
            name="why_me_name",
            field=models.CharField(default="Why me?", max_length=100),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="feedback_text",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="languagechoice",
            name="lang",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="occupationchoice",
            name="occupation",
            field=models.CharField(default="Backend", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_text",
            field=models.TextField(),
        ),
        migrations.AlterModelTable(
            name="hardskill",
            table="hard_skills",
        ),
        migrations.AlterModelTable(
            name="interest",
            table="interest",
        ),
        migrations.AlterModelTable(
            name="naturallanguage",
            table="natural_lang",
        ),
        migrations.AlterModelTable(
            name="softskill",
            table="soft_skills",
        ),
        migrations.CreateModel(
            name="UuidUrl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid_url",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "occupation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cvs.occupationchoice",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="blocknames",
            name="uuid_url",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cvs.uuidurl",
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="uuid_url",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cvs.uuidurl",
            ),
        ),
        migrations.AddField(
            model_name="education",
            name="uuid_url",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cvs.uuidurl",
            ),
        ),
        migrations.AddField(
            model_name="experience",
            name="uuid_url",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cvs.uuidurl",
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="uuid_url",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cvs.uuidurl",
            ),
        ),
        migrations.AddField(
            model_name="hardskill",
            name="uuid_url",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cvs.uuidurl",
            ),
        ),
        migrations.AddField(
            model_name="header",
            name="uuid_url",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cvs.uuidurl",
            ),
        ),
        migrations.AddField(
            model_name="interest",
            name="uuid_url",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cvs.uuidurl",
            ),
        ),
        migrations.AddField(
            model_name="manifest",
            name="uuid_url",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cvs.uuidurl",
            ),
        ),
        migrations.AddField(
            model_name="naturallanguage",
            name="uuid_url",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cvs.uuidurl",
            ),
        ),
        migrations.AddField(
            model_name="photos",
            name="uuid_url",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cvs.uuidurl",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="uuid_url",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cvs.uuidurl",
            ),
        ),
        migrations.AddField(
            model_name="softskill",
            name="uuid_url",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cvs.uuidurl",
            ),
        ),
        migrations.AddField(
            model_name="whyme",
            name="uuid_url",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cvs.uuidurl",
            ),
        ),
        migrations.AddConstraint(
            model_name="blocknames",
            constraint=models.UniqueConstraint(
                fields=("uuid_url", "lang"), name="unique_blocknames_per_uuid_and_lang"
            ),
        ),
        migrations.AddConstraint(
            model_name="header",
            constraint=models.UniqueConstraint(
                fields=("uuid_url", "lang"), name="unique_header_per_uuid_and_lang"
            ),
        ),
        migrations.AddConstraint(
            model_name="manifest",
            constraint=models.UniqueConstraint(
                fields=("uuid_url", "lang"), name="unique_manifest_per_uuid_and_lang"
            ),
        ),
        migrations.AddConstraint(
            model_name="naturallanguage",
            constraint=models.UniqueConstraint(
                fields=("uuid_url", "lang"),
                name="unique_natural_lang_per_uuid_and_lang",
            ),
        ),
        migrations.AddConstraint(
            model_name="whyme",
            constraint=models.UniqueConstraint(
                fields=("uuid_url", "lang"), name="unique_why_me_per_uuid_and_lang"
            ),
        ),
    ]
