# Generated by Django 5.2.1 on 2025-06-03 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cvs", "0014_rename_job_title_experience_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="lang",
            field=models.ForeignKey(
                default=4,
                on_delete=django.db.models.deletion.CASCADE,
                to="cvs.languagechoice",
            ),
            preserve_default=False,
        ),
    ]
