# Generated by Django 5.2.1 on 2025-06-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cvs", "0015_experience_lang"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
