# Generated by Django 5.2.1 on 2025-06-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cvs", "0016_experience_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experience",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
