# Generated by Django 5.2.1 on 2026-04-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cvs", "0016_languagechoice_user_occupationchoice_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="languagechoice",
            name="lang",
            field=models.CharField(default="eng", max_length=100),
        ),
    ]
