# Generated by Django 5.2.1 on 2026-04-21 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cvs", "0017_alter_languagechoice_lang"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="naturallanguage",
            name="unique_natural_lang_per_uuid_and_lang",
        ),
    ]
