# Generated by Django 5.2.1 on 2025-06-04 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cvs", "0017_alter_experience_end_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="softskill",
            name="lang",
            field=models.ForeignKey(
                default=4,
                on_delete=django.db.models.deletion.CASCADE,
                to="cvs.languagechoice",
            ),
            preserve_default=False,
        ),
    ]
