# Generated by Django 5.2.1 on 2025-06-04 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cvs", "0018_softskill_lang"),
    ]

    operations = [
        migrations.AddField(
            model_name="softskill",
            name="block_name",
            field=models.ForeignKey(
                default=4,
                on_delete=django.db.models.deletion.CASCADE,
                to="cvs.blocknames",
            ),
            preserve_default=False,
        ),
    ]
