# Generated by Django 5.2.1 on 2025-06-05 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cvs", "0022_experience_block_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="block_name",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.CASCADE,
                to="cvs.blocknames",
            ),
            preserve_default=False,
        ),
    ]
