# Generated by Django 5.2.1 on 2025-06-05 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cvs", "0023_project_block_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hobbyresume",
            name="hobby_id",
        ),
        migrations.RemoveField(
            model_name="hobbyresume",
            name="resume_id",
        ),
        migrations.RemoveField(
            model_name="blocknames",
            name="hobby_name",
        ),
        migrations.AddField(
            model_name="blocknames",
            name="interest_name",
            field=models.CharField(default="Interest", max_length=100),
        ),
        migrations.CreateModel(
            name="Interest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("interest_text", models.CharField(max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "Interest",
            },
        ),
        migrations.CreateModel(
            name="InterestResume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "interest_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cvs.interest"
                    ),
                ),
                (
                    "resume_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cvs.resume"
                    ),
                ),
            ],
            options={
                "db_table": "interest_resume",
            },
        ),
        migrations.AddField(
            model_name="interest",
            name="resume",
            field=models.ManyToManyField(through="cvs.InterestResume", to="cvs.resume"),
        ),
        migrations.DeleteModel(
            name="Hobby",
        ),
        migrations.DeleteModel(
            name="HobbyResume",
        ),
    ]
