# Generated by Django 5.2.1 on 2025-06-05 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cvs", "0024_remove_hobbyresume_hobby_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="interest",
            name="block_name",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.CASCADE,
                to="cvs.blocknames",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="interest",
            name="lang",
            field=models.ForeignKey(
                default=4,
                on_delete=django.db.models.deletion.CASCADE,
                to="cvs.languagechoice",
            ),
            preserve_default=False,
        ),
    ]
