# Generated by Django 5.2.1 on 2025-06-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cvs", "0025_interest_block_name_interest_lang"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blocknames",
            name="interest_name",
            field=models.CharField(default="Interests", max_length=100),
        ),
    ]
