# Generated by Django 5.2.1 on 2025-06-05 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cvs", "0026_alter_blocknames_interest_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="blocknames",
            name="natural_lang_name",
            field=models.CharField(default="Natural languages", max_length=100),
        ),
        migrations.CreateModel(
            name="NaturalLanguage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("natural_lang", models.CharField(default="Ukrainian", max_length=30)),
                ("level", models.CharField(default="fluent", max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "block_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cvs.blocknames"
                    ),
                ),
                (
                    "lang",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cvs.languagechoice",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
