HEADER_DEFAULTS_BY_LANG = {
    "eng": {
        "phone": "Write your cell phone",
        "first_name": "Write your first name",
        "second_name": "Write your second name",
        "email": "Write your email",
        "linkedin": "Paste your LinkedIn URL",
        "github": "Paste your GitHub URL",
        "country": "Write your country",
        "city": "Write your city",
        "district": "Write your district",
    },
    "rus": {
        "phone": "Укажите ваш номер телефона",
        "first_name": "Укажите ваше имя",
        "second_name": "Укажите вашу фамилию",
        "email": "Укажите ваш email",
        "linkedin": "Вставьте ссылку на ваш LinkedIn",
        "github": "Вставьте ссылку на ваш GitHub",
        "country": "Укажите вашу страну",
        "city": "Укажите ваш город",
        "district": "Укажите ваш район",
    },
    "ukr": {
        "phone": "Вкажіть ваш номер телефону",
        "first_name": "Вкажіть ваше ім'я",
        "second_name": "Вкажіть ваше прізвище",
        "email": "Вкажіть ваш email",
        "linkedin": "Вставте посилання на ваш LinkedIn",
        "github": "Вставте посилання на ваш GitHub",
        "country": "Вкажіть вашу країну",
        "city": "Вкажіть ваше місто",
        "district": "Вкажіть ваш район",
    },
}
